Adding new workflow based on blitz recipe

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,11 +1,17 @@
-name: Build, Lint, and Test
+name: CI
 
 on: [push]
 
 jobs:
-  build:
+  ###############
+  # Lint & Test
+  ###############
+  tests:
+    name: Tests
     runs-on: ubuntu-latest
-
+    env:
+      NODE_ENV: test
+      DATABASE_URL: mysql://root:password@127.0.0.1:3306/test
     services:
       mariadb:
         image: mariadb:latest
@@ -16,29 +22,80 @@ jobs:
           MYSQL_PASSWORD: password
           MYSQL_DATABASE: test
           MYSQL_ROOT_PASSWORD: password
-        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
+        options: >-
+          --health-cmd="mysqladmin ping"
+          --health-interval=5s
+          --health-timeout=2s
+          --health-retries=3
 
     steps:
-      - uses: actions/checkout@v1
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-      - name: Verify MariaDB connection
-        env:
-          PORT: ${{ job.services.mariadb.ports[3306] }}
-        run: |
-          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
-            sleep 1
-          done
-
-      - name: Use Node.js
-        uses: actions/setup-node@v1
+      # Node
+      - name: Read .node-version
+        id: node_version
+        run: echo ::set-output name=NODE_VERSION::$(cat .node-version || echo "14")
+      - name: Setup Node
+        uses: actions/setup-node@v2-beta
         with:
-          node-version: '12.x'
+          node-version: ${{ steps.node_version.outputs.NODE_VERSION }}
 
-      - name: Install dependencies
-        run: yarn install --frozen-lockfile --silent
+      # Yarn cache/install
+      - name: Find yarn cache location
+        id: yarn-cache
+        run: echo "::set-output name=dir::$(yarn cache dir)"
+      - name: JS package cache
+        uses: actions/cache@v2
+        with:
+          path: |
+            ${{ steps.yarn-cache.outputs.dir }}
+            **/node_modules
+            /home/runner/.cache/Cypress
+            C:\Users\runneradmin\AppData\Local\Cypress\Cache
+          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
+          restore-keys: |
+            ${{ runner.os }}-yarn-
+      - name: Install packages
+        run: yarn install --frozen-lockfile
 
-      - name: yarn lint
+      # Lint Code
+      - name: Lint
         run: yarn lint
 
-      - name: yarn test
+      # Migrate DB & generate prisma client
+      - name: Migrate DB & generate prisma client
+        run: yarn blitz prisma migrate dev --preview-feature
+
+      # Jest Tests (API/Frontend)
+      - name: Run Jest Tests
         run: yarn test
+
+      # E2E Tests via Cypress
+      # - name: Run Cypress E2E Tests
+      #   uses: cypress-io/github-action@v2
+      #   with:
+      #     # we have already installed all dependencies above
+      #     install: false
+      #     start: yarn test:server --production
+      #     wait-on: "http://localhost:3099"
+      #     wait-on-timeout: 300
+      #   env:
+      #     NODE_ENV: test
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      # - name: Upload Cypress Screenshots
+      #   uses: actions/upload-artifact@v1
+      #   # Only capture images on failure
+      #   if: failure()
+      #   with:
+      #     name: cypress-screenshots
+      #     path: cypress/screenshots
+      #     retention-days: 3
+      # - name: Upload Cypress Videos
+      #   uses: actions/upload-artifact@v1
+      #   # Test run video was always captured, so this action uses "always()" condition
+      #   if: always()
+      #   with:
+      #     name: cypress-videos
+      #     path: cypress/videos
+      #     retention-days: 3
